name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "latest"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Check linter and code formatter
        run: uv run --frozen ruff check

      - name: Test with Python ${{ matrix.python-version }}
        run: uv run --frozen pytest
